/**
 * upload-render.js
 *
 * Uploads the Remotion-rendered video (out/video.mp4) to Appwrite Storage,
 * then calls the webhook to notify the application backend.
 *
 * Environment variables required (set in GitHub Actions secrets):
 *   APPWRITE_VIDEO_ENDPOINT   – e.g. https://fra.cloud.appwrite.io/v1
 *   APPWRITE_VIDEO_PROJECT_ID – Your Appwrite project ID
 *   APPWRITE_VIDEO_API_KEY    – Server API key with storage.write scope
 *   APPWRITE_VIDEO_BUCKET_ID  – Target storage bucket ID
 *   VIDEO_ID                  – The videoId generated by the Inngest pipeline
 *   WEBHOOK_URL               – The application endpoint to PATCH when done
 */

const sdk = require('node-appwrite');
const { InputFile } = require('node-appwrite/file');
const fs   = require('fs');
const path = require('path');

async function upload() {
    // ── Config ──────────────────────────────────────────────────────────────
    const filePath   = path.join(process.cwd(), 'out/video.mp4');
    const videoId    = process.env.VIDEO_ID;
    const webhookUrl = process.env.WEBHOOK_URL;

    const endpoint  = (process.env.APPWRITE_VIDEO_ENDPOINT || process.env.APPWRITE_ENDPOINT || '').replace(/\/$/, '');
    const projectId = process.env.APPWRITE_VIDEO_PROJECT_ID || process.env.APPWRITE_PROJECT_ID;
    const apiKey    = process.env.APPWRITE_VIDEO_API_KEY    || process.env.APPWRITE_API_KEY;
    const bucketId  = process.env.APPWRITE_VIDEO_BUCKET_ID  || process.env.APPWRITE_BUCKET_ID;

    // ── Guards ───────────────────────────────────────────────────────────────
    if (!videoId) {
        console.error('❌ Missing VIDEO_ID');
        process.exit(1);
    }
    if (!endpoint || !projectId || !apiKey || !bucketId) {
        console.error('❌ Missing Appwrite env vars (APPWRITE_VIDEO_ENDPOINT / PROJECT_ID / API_KEY / BUCKET_ID)');
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }
    if (!fs.existsSync(filePath)) {
        console.error('❌ Rendered file not found:', filePath);
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }

    // ── Appwrite client ──────────────────────────────────────────────────────
    const client = new sdk.Client()
        .setEndpoint(endpoint)
        .setProject(projectId)
        .setKey(apiKey);

    const storage = new sdk.Storage(client);

    const finalSizeBytes   = fs.statSync(filePath).size;
    const fileSizeMB       = (finalSizeBytes / 1024 / 1024).toFixed(1);
    const CHUNK_SIZE_BYTES = 44 * 1024 * 1024; // 44 MB — stays under Appwrite 50 MB limit

    console.log(`☁️  Uploading ${filePath} (${fileSizeMB} MB) → Appwrite Storage (bucket: ${bucketId})...`);

    try {
        if (finalSizeBytes > CHUNK_SIZE_BYTES) {
            // ── Chunked upload ───────────────────────────────────────────────
            const totalChunks = Math.ceil(finalSizeBytes / CHUNK_SIZE_BYTES);
            console.log(`✂️  Raw-binary splitting → ${totalChunks} chunks of ≤44 MB...`);

            const chunksDir = path.join(path.dirname(filePath), 'video-chunks');
            fs.mkdirSync(chunksDir, { recursive: true });

            const inFd     = fs.openSync(filePath, 'r');
            const chunkIds = [];
            const BUF_SIZE = 8 * 1024 * 1024;
            const buf      = Buffer.allocUnsafe(BUF_SIZE);

            try {
                for (let i = 0; i < totalChunks; i++) {
                    const chunkName = `chunk-${String(i).padStart(3, '0')}.bin`;
                    const chunkPath = path.join(chunksDir, chunkName);
                    const outFd     = fs.openSync(chunkPath, 'w');
                    let bytesWritten = 0;

                    while (bytesWritten < CHUNK_SIZE_BYTES) {
                        const toRead   = Math.min(BUF_SIZE, CHUNK_SIZE_BYTES - bytesWritten);
                        const bytesRead = fs.readSync(inFd, buf, 0, toRead, null);
                        if (bytesRead === 0) break;
                        fs.writeSync(outFd, buf, 0, bytesRead);
                        bytesWritten += bytesRead;
                    }
                    fs.closeSync(outFd);

                    const cleanVideoId = videoId.replace(/[^a-zA-Z0-9._-]/g, '-');
                    const chunkFileId  = `v-${cleanVideoId.slice(0, 28)}-${i}`.slice(0, 36);

                    // Delete stale file if it already exists (idempotent retry)
                    try { await storage.deleteFile({ bucketId, fileId: chunkFileId }); } catch { /* not found — fine */ }

                    console.log(`   [${i + 1}/${totalChunks}] Uploading ${chunkName} as ${chunkFileId}...`);
                    await storage.createFile({
                        bucketId,
                        fileId: chunkFileId,
                        file: InputFile.fromPath(chunkPath, chunkName),
                    });
                    chunkIds.push(chunkFileId);
                }
                fs.closeSync(inFd);

                const videoUrl = JSON.stringify({
                    chunked: true,
                    rawBinary: true,
                    count: totalChunks,
                    ids: chunkIds,
                    bucketId,
                    endpoint,
                    projectId,
                });

                console.log('✅ Chunked upload complete. videoUrl metadata:', videoUrl);
                if (webhookUrl) await notifyWebhook(webhookUrl, videoId, videoUrl, 'completed');

                try { fs.rmSync(chunksDir, { recursive: true, force: true }); } catch {}
                console.log('🎉 Done!');
                process.exit(0);

            } catch (chunkErr) {
                try { fs.closeSync(inFd); } catch {}
                try { fs.rmSync(chunksDir, { recursive: true, force: true }); } catch {}
                throw chunkErr;
            }

        } else {
            // ── Single-file upload ───────────────────────────────────────────
            const filename    = `${videoId}.mp4`;
            const cleanVideoId = videoId.replace(/[^a-zA-Z0-9._-]/g, '-').slice(0, 36);

            // Delete stale file if it already exists (idempotent retry)
            try { await storage.deleteFile({ bucketId, fileId: cleanVideoId }); } catch { /* not found — fine */ }

            const result = await storage.createFile({
                bucketId,
                fileId: cleanVideoId,
                file: InputFile.fromPath(filePath, filename),
            });

            const videoUrl = `${endpoint}/storage/buckets/${bucketId}/files/${result.$id}/view?project=${projectId}`;
            console.log('✅ Video uploaded successfully:', videoUrl);

            if (webhookUrl) await notifyWebhook(webhookUrl, videoId, videoUrl, 'completed');
            console.log('🎉 Done!');
            process.exit(0);
        }

    } catch (error) {
        console.error('❌ Upload failed:', error?.message ?? error);
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }
}

async function notifyWebhook(webhookUrl, videoId, videoUrl, status) {
    try {
        console.log(`📡 Calling webhook: ${webhookUrl} (status: ${status})`);
        const secret  = process.env.WEBHOOK_SECRET;
        const headers = { 'Content-Type': 'application/json' };
        if (secret) headers['Authorization'] = `Bearer ${secret}`;
        const response = await fetch(webhookUrl, {
            method: 'PATCH',
            headers,
            body: JSON.stringify({ videoId, videoUrl, status }),
        });

        if (response.ok) {
            console.log('✅ Webhook notified successfully');
        } else {
            console.error('⚠️  Webhook notification failed:', await response.text());
        }
    } catch (err) {
        console.error('⚠️  Webhook call error:', err?.message ?? err);
    }
}

upload();
