/**
 * upload-render.js
 *
 * Uploads the Remotion-rendered video (out/video.mp4) to Appwrite Storage,
 * then calls the webhook to notify the application backend.
 *
 * Environment variables required (set in GitHub Actions secrets):
 *   APPWRITE_ENDPOINT   – e.g. https://fra.cloud.appwrite.io/v1
 *   APPWRITE_PROJECT_ID – Your Appwrite project ID
 *   APPWRITE_API_KEY    – Server API key with storage.write scope
 *   APPWRITE_BUCKET_ID  – Target storage bucket ID
 *   VIDEO_ID            – The videoId generated by the Inngest pipeline
 *   WEBHOOK_URL         – The application endpoint to PATCH when done
 */

const sdk = require('node-appwrite');
const { InputFile } = require('node-appwrite/file');
const fs   = require('fs');
const path = require('path');

async function upload() {
    // ── Config ──────────────────────────────────────────────────────────────
    const filePath   = path.join(process.cwd(), 'out/video.mp4');
    const videoId    = process.env.VIDEO_ID;
    const webhookUrl = process.env.WEBHOOK_URL;

    const endpoint   = (process.env.APPWRITE_ENDPOINT || '').replace(/\/$/, '');
    const projectId  = process.env.APPWRITE_PROJECT_ID;
    const apiKey     = process.env.APPWRITE_API_KEY;
    const bucketId   = process.env.APPWRITE_BUCKET_ID;

    // ── Guard: required env vars ─────────────────────────────────────────────
    if (!videoId) {
        console.error('❌ Missing VIDEO_ID');
        process.exit(1);
    }
    if (!endpoint || !projectId || !apiKey || !bucketId) {
        console.error('❌ Missing one or more Appwrite env vars: APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY, APPWRITE_BUCKET_ID');
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }

    // ── Guard: file must exist ───────────────────────────────────────────────
    if (!fs.existsSync(filePath)) {
        console.error('❌ Rendered file not found:', filePath);
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }

    // ── Appwrite client ──────────────────────────────────────────────────────
    const client = new sdk.Client()
        .setEndpoint(endpoint)
        .setProject(projectId)
        .setKey(apiKey);

    const storage = new sdk.Storage(client);

    // ── Upload ───────────────────────────────────────────────────────────────
    console.log(`☁️  Uploading ${filePath} → Appwrite Storage (bucket: ${bucketId})...`);
    const fileBuffer = fs.readFileSync(filePath);
    const filename   = `${videoId}.mp4`;

    try {
        const result = await storage.createFile({
            bucketId,
            fileId: sdk.ID.unique(),
            file: InputFile.fromBuffer(fileBuffer, filename, 'video/mp4'),
        });

        // Construct public view URL
        const videoUrl = `${endpoint}/storage/buckets/${bucketId}/files/${result.$id}/view?project=${projectId}`;
        console.log('✅ Video uploaded successfully:', videoUrl);

        if (webhookUrl) {
            await notifyWebhook(webhookUrl, videoId, videoUrl, 'completed');
        }

        console.log('🎉 Done!');
        process.exit(0);
    } catch (error) {
        console.error('❌ Upload failed:', error?.message ?? error);
        if (webhookUrl) await notifyWebhook(webhookUrl, videoId, null, 'failed');
        process.exit(1);
    }
}

async function notifyWebhook(webhookUrl, videoId, videoUrl, status) {
    try {
        console.log(`📡 Calling webhook: ${webhookUrl} (status: ${status})`);
        const response = await fetch(webhookUrl, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ videoId, videoUrl, status }),
        });

        if (response.ok) {
            console.log('✅ Webhook notified successfully');
        } else {
            console.error('⚠️  Webhook notification failed:', await response.text());
        }
    } catch (err) {
        console.error('⚠️  Webhook call error:', err?.message ?? err);
    }
}

upload();
